---
# vars file for monitoring

docker_images:
  prometheus: "prom/prometheus:latest"
  grafana: "grafana/grafana:main"
  node_exporter: "prom/node-exporter:latest"
  cadvisor: "gcr.io/cadvisor/cadvisor:latest"
  blackbox_exporter: "prom/blackbox-exporter:latest"

service_ports:
  prometheus: 9090
  grafana: 3000
  node_exporter: 9100
  cadvisor: 8181                    
  blackbox_exporter: 9115

prometheus_scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['app-server-ip:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['app-server-ip:8181']
  - job_name: 'blackbox'
    static_configs:
      - targets: ['monitoring-server-ip:9115']
