- name: Assemble Consul cluster
  hosts: consul_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - ansible-consul

- name: Consul client and service
  hosts: 89.169.154.146
  vars_files:
    - consul_services_v1.yaml
    - consul_services_v2.yaml
  any_errors_fatal: true
  become: true
  become_user: root
  roles: 
    - ansible-consul
  
- name: Nginx install
  hosts: nginx
  become: true
  become_user: root
  roles: 
    - ansible-role-nginx