- name: Deploy monitoring for app_server
  hosts: app_ext
  become: true
  roles: 
    - monitoring
  vars:
    deploy_node: true
    deploy_cadvisor: true
    deploy_blackbox: true
    deploy_prometheus: false
    deploy_grafana: false

- name: Deploy monitoring for prometheus_grafana
  hosts: monitoring_ext
  become: true
  roles: 
    - monitoring
  vars:
    deploy_node: true
    deploy_cadvisor: true
    deploy_blackbox: false
    deploy_prometheus: true
    deploy_grafana: true
